// media — typed access to Dayflow's generated media assets.
//
// The manifest (src/data/media-manifest.json) is REGENERATED by
// `node scripts/sync-media.mjs` whenever assets are dropped into
// public/media/. It only ever lists files that actually exist, so
// every helper below can return null and callers fall back to the
// tokenized placeholder UI. Nothing here knows about bundles or
// remote hosts — assets are plain static files under /media/.
//
// Layout contract (see docs/media-assets.md):
//   public/media/exercises/<slug>.<ext>   one illustration per exercise
//   public/media/body-parts/<slug>.<ext>  per-body-part hero art
//   public/media/areas/<slug>.<ext>       everything else (sleep hero,
//                                         empty states, badges, …)

import raw from "@/data/media-manifest.json";

interface MediaManifest {
  v: 1;
  exercises: Record<string, string>;
  bodyParts: Record<string, string>;
  areas: Record<string, string>;
}

const manifest = raw as unknown as MediaManifest;

/** Same slug rules as scripts/sync-media.mjs — keep them in lockstep. */
export const slugify = (name: string): string =>
  name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

/** Exercise illustration by display name, or null when not generated yet. */
export function exerciseImageByName(name: string): string | null {
  return manifest.exercises[slugify(name)] ?? null;
}

/** Per-body-part art ("chest", "upper legs", …), or null. */
export function bodyPartImage(bodyPart: string): string | null {
  return manifest.bodyParts[slugify(bodyPart)] ?? null;
}

/** Area / hero / empty-state art by slug ("sleep-hero", …), or null. */
export function areaImage(slug: string): string | null {
  return manifest.areas[slugify(slug)] ?? null;
}
