import type { Metadata } from "next";
import Link from "next/link";
import "@/styles/legal.css";

// ============================================================
// Focus Triad — Terms of Service (audit P0-2)
// ------------------------------------------------------------
// Public, static, signed-out reachable. Plain-language terms
// that match the product: a self-tracking tool, not a medical
// device, billed (when billed) through NOWPayments.
// ============================================================

export const metadata: Metadata = {
  title: "Terms of Service — Focus Triad",
  description:
    "The terms for using Focus Triad: what the service is, what you agree to, how billing works, and the limits of liability.",
  robots: { index: true, follow: true },
};

export default function TermsPage() {
  return (
    <main className="legal">
      <div className="legal-inner">
        <div className="legal-top">
          <Link href="/" className="legal-brand">
            <svg width="22" height="22" viewBox="0 0 24 24" aria-hidden="true">
              <path
                d="M4 15c3-7 5-7 8 0s5 7 8 0"
                fill="none"
                stroke="currentColor"
                strokeWidth="2.4"
                strokeLinecap="round"
              />
            </svg>
            Focus Triad
          </Link>
          <Link href="/" className="legal-back">
            <svg width="14" height="14" viewBox="0 0 24 24" aria-hidden="true">
              <path
                d="M15 5l-7 7 7 7"
                fill="none"
                stroke="currentColor"
                strokeWidth="2.4"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
            Back
          </Link>
        </div>

        <h1>Terms of Service</h1>
        <p className="legal-updated">Last updated: October 10, 2026</p>

        <h2>1. What Focus Triad is</h2>
        <p>
          Focus Triad is a personal life-tracking application: timelines, logs,
          habit streaks, reviews, and an AI coach grounded in what you record.
          By creating an account (or continuing as a guest) you agree to these
          terms. If you don&rsquo;t agree, please don&rsquo;t use the service —
          and know that you can export and delete your data at any time on the
          way out.
        </p>

        <h2>2. Your account</h2>
        <p>
          You are responsible for your credentials and for what happens under
          your account. Keep your password private. You can delete your account
          at any time from Settings, which erases your data permanently. Guest
          sessions live on your device until you clear them or upgrade them to
          a full account.
        </p>

        <h2>3. Acceptable use</h2>
        <ul>
          <li>Use Focus Triad lawfully and only for your own tracking.</li>
          <li>
            Don&rsquo;t attempt to access other users&rsquo; data, probe or
            break the service, or automate abuse of the AI coach or voice
            features.
          </li>
          <li>
            Don&rsquo;t use the service to store content that is illegal or
            harmful to others.
          </li>
        </ul>
        <p>
          We may suspend accounts that abuse the service (for example, by
            exhausting shared AI quotas deliberately), and we will tell you why
          when we do.
        </p>

        <h2>4. The AI coach</h2>
        <p>
          Coaching replies are generated by AI models from the context you
          provide. They can be wrong, generic, or off — treat them as
          suggestions from a well-read friend, not professional advice. Nothing
          in the app is medical, psychological, nutritional, legal, or financial
          advice. If a topic is serious, the coach will point you to real
          professionals, and so do we.
        </p>

        <h2>5. Billing</h2>
        <p>
          The core of Focus Triad is free. If you choose a paid plan (Focus Triad
          Plus), payments are processed by our payment provider (NOWPayments);
          we never see or store your card details or wallet keys. Paid features
          are granted while your payment stands; if a payment fails or is
          refunded, the paid features end — your logged data always remains
          yours, exportable, and never held hostage.
        </p>

        <h2>6. Data and availability</h2>
        <p>
          Your logs are stored as described in our{" "}
          <Link href="/privacy">Privacy Policy</Link>. We work hard on
          reliability, but the service is provided &ldquo;as is&rdquo; without
          warranties of uninterrupted availability. Keep your own exports if
          your records matter to you — the export tool exists for exactly that.
        </p>

        <h2>7. Liability</h2>
        <p>
          To the maximum extent permitted by law, Focus Triad&rsquo;s makers are
          not liable for indirect or consequential damages, lost data beyond
          what backups can restore, or outcomes of decisions you made based on
          app content (including AI coaching). Where liability cannot be
          excluded, it is limited to the amount you paid us in the twelve
          months before the claim — which, for the free plan, is nothing.
        </p>

        <h2>8. Changes</h2>
        <p>
          The service evolves, and so may these terms. If a change is material
          we will surface it in the app before it takes effect. Continuing to
          use Focus Triad after a change means you accept it.
        </p>

        <h2>9. Contact</h2>
        <p>
          Questions about these terms:{" "}
          <a href="mailto:support@focustriad.app">support@focustriad.app</a>.
        </p>
      </div>
    </main>
  );
}
