// ============================================================
// Dayflow AI — Liquid Glass map generator (PRD §6.2, Phase 5 T3)
// ------------------------------------------------------------
// Emits the precomputed displacement + specular maps as inline
// SVG data-URLs, one pair per T1 variant (dock / cta). Run once
// at build time (node scripts/gen-lg-maps.mjs); the output is
// pasted into src/components/ui/LiquidGlass.tsx as constants so
// the runtime never generates anything.
//
// Displacement map encoding (feDisplacementMap R/G channels):
//   neutral   = rgb(127,127,127)  -> no shift
//   left edge = R>127 (push +x), right edge = R<127 (push -x)
//   top edge  = G>127 (push +y), bottom edge = G<127 (push -y)
// The 22% edge strips bend the backdrop inward — the classic
// liquid-glass edge refraction.
// Specular map: rim-biased diagonal gradient (white top-left to
// transparent bottom-right) used by the feComposite rim stage.
// ============================================================

const EDGE = 0.22; // fraction of each edge that refracts

const displacementMap = (size) => {
  const strip = Math.round(size * EDGE);
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}">
  <defs>
    <linearGradient id="hL" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="rgb(255,127,127)"/><stop offset="1" stop-color="rgb(127,127,127)"/>
    </linearGradient>
    <linearGradient id="hR" x1="1" y1="0" x2="0" y2="0">
      <stop offset="0" stop-color="rgb(0,127,127)"/><stop offset="1" stop-color="rgb(127,127,127)"/>
    </linearGradient>
    <linearGradient id="vT" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="rgb(127,255,127)"/><stop offset="1" stop-color="rgb(127,127,127)"/>
    </linearGradient>
    <linearGradient id="vB" x1="0" y1="1" x2="0" y2="0">
      <stop offset="0" stop-color="rgb(127,0,127)"/><stop offset="1" stop-color="rgb(127,127,127)"/>
    </linearGradient>
  </defs>
  <rect width="${size}" height="${size}" fill="rgb(127,127,127)"/>
  <rect y="${size - strip}" width="${size}" height="${strip}" fill="url(#vB)"/>
  <rect width="${size}" height="${strip}" fill="url(#vT)"/>
  <rect x="${size - strip}" width="${strip}" height="${size}" fill="url(#hR)"/>
  <rect width="${strip}" height="${size}" fill="url(#hL)"/>
</svg>`;
};

const specularMap = (size) => `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}">
  <defs>
    <linearGradient id="rim" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="rgba(255,255,255,0.9)"/>
      <stop offset="0.28" stop-color="rgba(255,255,255,0.25)"/>
      <stop offset="0.6" stop-color="rgba(255,255,255,0)"/>
      <stop offset="1" stop-color="rgba(255,255,255,0.35)"/>
    </linearGradient>
  </defs>
  <rect width="${size}" height="${size}" fill="url(#rim)"/>
</svg>`;

const toDataUrl = (svg) =>
  `data:image/svg+xml,${encodeURIComponent(svg).replace(/'/g, "%27").replace(/"/g, "%22")}`;

console.log("/* Generated by scripts/gen-lg-maps.mjs — do not edit by hand. */");
console.log(`export const DISPLACEMENT_MAP_DOCK = "${toDataUrl(displacementMap(64))}";`);
console.log(`export const DISPLACEMENT_MAP_CTA = "${toDataUrl(displacementMap(48))}";`);
console.log(`export const SPECULAR_MAP = "${toDataUrl(specularMap(64))}";`);
