"use client";

// ============================================================
// Dayflow AI — Liquid Glass T1 primitive (PRD §6.2, Phase 5 T3)
// ------------------------------------------------------------
// Signature material on EXACTLY two surfaces (hard budget):
//   1. the mobile tab dock          -> variant "dock"
//   2. the Habits primary Log CTA   -> variant "cta"
// Never inside scroll containers; content cards stay T0.
//
// Pipeline per §6.2 (both variants, fixed-size):
//   feGaussianBlur -> feImage(map) -> feDisplacementMap(R,G)
//   -> feColorMatrix(saturate) -> feComposite(rim) -> feBlend
//
// The displacement + specular maps are PRECOMPUTED at build time
// by scripts/gen-lg-maps.mjs and inlined below as data-URLs —
// the runtime never generates anything.
//
// Capability matrix:
//   Chromium  -> SVG-filter backdrop reference  (true refraction)
//   Safari/Firefox -> backdrop-copy approximation: T0 frost +
//                rim gradient layer clipped to the element shape
//                (opacity --lg-rim-opacity); degrades to T0.
// ============================================================

import { useSyncExternalStore, type CSSProperties, type ReactNode } from "react";
import { cn } from "@/lib/utils";

/* Generated by scripts/gen-lg-maps.mjs — do not edit by hand. */
export const DISPLACEMENT_MAP_DOCK = "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2264%22%20height%3D%2264%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22hL%22%20x1%3D%220%22%20y1%3D%220%22%20x2%3D%221%22%20y2%3D%220%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%22%20stop-color%3D%22rgb(255%2C127%2C127)%22%2F%3E%3Cstop%20offset%3D%221%22%20stop-color%3D%22rgb(127%2C127%2C127)%22%2F%3E%0A%20%20%20%20%3C%2FlinearGradient%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22hR%22%20x1%3D%221%22%20y1%3D%220%22%20x2%3D%220%22%20y2%3D%220%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%22%20stop-color%3D%22rgb(0%2C127%2C127)%22%2F%3E%3Cstop%20offset%3D%221%22%20stop-color%3D%22rgb(127%2C127%2C127)%22%2F%3E%0A%20%20%20%20%3C%2FlinearGradient%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22vT%22%20x1%3D%220%22%20y1%3D%220%22%20x2%3D%220%22%20y2%3D%221%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%22%20stop-color%3D%22rgb(127%2C255%2C127)%22%2F%3E%3Cstop%20offset%3D%221%22%20stop-color%3D%22rgb(127%2C127%2C127)%22%2F%3E%0A%20%20%20%20%3C%2FlinearGradient%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22vB%22%20x1%3D%220%22%20y1%3D%221%22%20x2%3D%220%22%20y2%3D%220%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%22%20stop-color%3D%22rgb(127%2C0%2C127)%22%2F%3E%3Cstop%20offset%3D%221%22%20stop-color%3D%22rgb(127%2C127%2C127)%22%2F%3E%0A%20%20%20%20%3C%2FlinearGradient%3E%0A%20%20%3C%2Fdefs%3E%0A%20%20%3Crect%20width%3D%2264%22%20height%3D%2264%22%20fill%3D%22rgb(127%2C127%2C127)%22%2F%3E%0A%20%20%3Crect%20y%3D%2250%22%20width%3D%2264%22%20height%3D%2214%22%20fill%3D%22url(%23vB)%22%2F%3E%0A%20%20%3Crect%20width%3D%2264%22%20height%3D%2214%22%20fill%3D%22url(%23vT)%22%2F%3E%0A%20%20%3Crect%20x%3D%2250%22%20width%3D%2214%22%20height%3D%2264%22%20fill%3D%22url(%23hR)%22%2F%3E%0A%20%20%3Crect%20width%3D%2214%22%20height%3D%2264%22%20fill%3D%22url(%23hL)%22%2F%3E%0A%3C%2Fsvg%3E";
export const DISPLACEMENT_MAP_CTA = "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2248%22%20height%3D%2248%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22hL%22%20x1%3D%220%22%20y1%3D%220%22%20x2%3D%221%22%20y2%3D%220%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%22%20stop-color%3D%22rgb(255%2C127%2C127)%22%2F%3E%3Cstop%20offset%3D%221%22%20stop-color%3D%22rgb(127%2C127%2C127)%22%2F%3E%0A%20%20%20%20%3C%2FlinearGradient%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22hR%22%20x1%3D%221%22%20y1%3D%220%22%20x2%3D%220%22%20y2%3D%220%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%22%20stop-color%3D%22rgb(0%2C127%2C127)%22%2F%3E%3Cstop%20offset%3D%221%22%20stop-color%3D%22rgb(127%2C127%2C127)%22%2F%3E%0A%20%20%20%20%3C%2FlinearGradient%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22vT%22%20x1%3D%220%22%20y1%3D%220%22%20x2%3D%220%22%20y2%3D%221%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%22%20stop-color%3D%22rgb(127%2C255%2C127)%22%2F%3E%3Cstop%20offset%3D%221%22%20stop-color%3D%22rgb(127%2C127%2C127)%22%2F%3E%0A%20%20%20%20%3C%2FlinearGradient%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22vB%22%20x1%3D%220%22%20y1%3D%221%22%20x2%3D%220%22%20y2%3D%220%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%22%20stop-color%3D%22rgb(127%2C0%2C127)%22%2F%3E%3Cstop%20offset%3D%221%22%20stop-color%3D%22rgb(127%2C127%2C127)%22%2F%3E%0A%20%20%20%20%3C%2FlinearGradient%3E%0A%20%20%3C%2Fdefs%3E%0A%20%20%3Crect%20width%3D%2248%22%20height%3D%2248%22%20fill%3D%22rgb(127%2C127%2C127)%22%2F%3E%0A%20%20%3Crect%20y%3D%2237%22%20width%3D%2248%22%20height%3D%2211%22%20fill%3D%22url(%23vB)%22%2F%3E%0A%20%20%3Crect%20width%3D%2248%22%20height%3D%2211%22%20fill%3D%22url(%23vT)%22%2F%3E%0A%20%20%3Crect%20x%3D%2237%22%20width%3D%2211%22%20height%3D%2248%22%20fill%3D%22url(%23hR)%22%2F%3E%0A%20%20%3Crect%20width%3D%2211%22%20height%3D%2248%22%20fill%3D%22url(%23hL)%22%2F%3E%0A%3C%2Fsvg%3E";
export const SPECULAR_MAP = "data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2264%22%20height%3D%2264%22%3E%0A%20%20%3Cdefs%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22rim%22%20x1%3D%220%22%20y1%3D%220%22%20x2%3D%221%22%20y2%3D%221%22%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220%22%20stop-color%3D%22rgba(255%2C255%2C255%2C0.9)%22%2F%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220.28%22%20stop-color%3D%22rgba(255%2C255%2C255%2C0.25)%22%2F%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%220.6%22%20stop-color%3D%22rgba(255%2C255%2C255%2C0)%22%2F%3E%0A%20%20%20%20%20%20%3Cstop%20offset%3D%221%22%20stop-color%3D%22rgba(255%2C255%2C255%2C0.35)%22%2F%3E%0A%20%20%20%20%3C%2FlinearGradient%3E%0A%20%20%3C%2Fdefs%3E%0A%20%20%3Crect%20width%3D%2264%22%20height%3D%2264%22%20fill%3D%22url(%23rim)%22%2F%3E%0A%3C%2Fsvg%3E";

export type LiquidGlassVariant = "dock" | "cta";

/** Map + displacement scale per fixed-size variant (§6.2). */
const VARIANT_CONFIG: Record<
  LiquidGlassVariant,
  { map: string; scale: number; blur: number }
> = {
  dock: { map: DISPLACEMENT_MAP_DOCK, scale: 26, blur: 6 },
  cta: { map: DISPLACEMENT_MAP_CTA, scale: 18, blur: 4 },
};

/** One <filter> per variant — rendered once via <LiquidGlassFilters/>. */
function LiquidGlassFilterDef({ variant }: { variant: LiquidGlassVariant }) {
  const { map, scale, blur } = VARIANT_CONFIG[variant];
  const id = `lg-${variant}`;
  return (
    <filter
      id={id}
      x="-8%"
      y="-8%"
      width="116%"
      height="116%"
      colorInterpolationFilters="sRGB"
    >
      {/* 1 — soften the backdrop before bending it */}
      <feGaussianBlur stdDeviation={blur} in="SourceGraphic" result="blur" />
      {/* 2 — precomputed displacement map, stretched to the element */}
      <feImage
        href={map}
        result="map"
        preserveAspectRatio="none"
        x="0"
        y="0"
        width="100%"
        height="100%"
      />
      {/* 3 — edge refraction (R = x shift, G = y shift) */}
      <feDisplacementMap
        in="blur"
        in2="map"
        scale={scale}
        xChannelSelector="R"
        yChannelSelector="G"
        result="displaced"
      />
      {/* 4 — glass saturate */}
      <feColorMatrix type="saturate" values="1.7" in="displaced" result="saturated" />
      {/* 5 — specular rim, clipped to the element shape */}
      <feImage
        href={SPECULAR_MAP}
        result="spec"
        preserveAspectRatio="none"
        x="0"
        y="0"
        width="100%"
        height="100%"
      />
      <feComposite in="spec" in2="SourceAlpha" operator="in" result="rim" />
      {/* 6 — blend rim light over the refracted backdrop */}
      <feBlend in="saturated" in2="rim" mode="screen" />
    </filter>
  );
}

/**
 * Mount once in the app shell: both variant filter defs live in a
 * zero-footprint SVG so the per-variant filter references resolve
 * document-wide.
 */
export function LiquidGlassFilters() {
  return (
    <svg
      aria-hidden="true"
      focusable="false"
      width="0"
      height="0"
      style={{ position: "absolute", pointerEvents: "none" }}
    >
      <defs>
        <LiquidGlassFilterDef variant="dock" />
        <LiquidGlassFilterDef variant="cta" />
      </defs>
    </svg>
  );
}

/**
 * True when the platform can apply an SVG filter chain to the
 * backdrop (Chromium). Safari/Firefox return false and get the
 * backdrop-copy approximation below.
 */
const supportsSvgBackdropFilter = (): boolean => {
  if (typeof window === "undefined" || !window.CSS?.supports) return false;
  try {
    return window.CSS.supports("backdrop-filter", "url(#probe)");
  } catch {
    return false;
  }
};

// getSnapshot must be cheap and stable — probe once, cache forever.
let cachedBackdropProbe: boolean | null = null;
const snapshotBackdropSupport = (): boolean => {
  if (cachedBackdropProbe === null) cachedBackdropProbe = supportsSvgBackdropFilter();
  return cachedBackdropProbe;
};

const emptySubscribe = () => () => {};

/**
 * Client-only capability gate via useSyncExternalStore: the server
 * snapshot (false) is also used for the hydration render, so SSR and
 * client markup stay identical — evaluating window.CSS during render
 * is exactly the server/client branch that trips React #418. React
 * swaps in the real client value right after hydration.
 */
const useChromiumBackdrop = (): boolean =>
  useSyncExternalStore(
    emptySubscribe,
    snapshotBackdropSupport,
    () => false
  );

export interface LiquidGlassProps {
  /** The exact Chromium filter value — carries the variant filter reference. */
  filterCss: string;
  children?: ReactNode;
  className?: string;
  style?: CSSProperties;
  /** Override the rim opacity (default: var(--lg-rim-opacity)). */
  rimOpacity?: number;
  [key: string]: unknown;
}

/**
 * The T1 surface. Chromium applies the SVG filter chain to the
 * backdrop (the exact value arrives via filterCss so each usage
 * site owns its variant reference); every other engine gets the
 * T0 frost + a specular rim layer clipped to the element shape.
 */
export function LiquidGlass({
  filterCss,
  children,
  className,
  style,
  rimOpacity,
  ...rest
}: LiquidGlassProps) {
  const chromium = useChromiumBackdrop();

  const surfaceStyle: CSSProperties = chromium
    ? {
        backdropFilter: filterCss,
        WebkitBackdropFilter: filterCss,
      }
    : {
        // Backdrop-copy approximation: T0 frost carries the depth,
        // the rim layer below carries the specular signature.
        backdropFilter: "blur(18px) saturate(1.7)",
        WebkitBackdropFilter: "blur(18px) saturate(1.7)",
      };

  return (
    <div
      {...(rest as Record<string, unknown>)}
      className={cn("relative", className)}
      style={{
        ...surfaceStyle,
        borderRadius: "var(--lg-radius)",
        transform: "translateZ(0)",
        willChange: "transform",
        ...style,
      }}
    >
      {/* Rim layer — clipped to the shape by the surface's radius + overflow */}
      {!chromium && (
        <span
          aria-hidden="true"
          className="pointer-events-none absolute inset-0"
          style={{
            borderRadius: "inherit",
            background:
              "linear-gradient(135deg, color-mix(in srgb, var(--df-white) 50%, transparent), color-mix(in srgb, var(--df-white) 8%, transparent) 30%, transparent 55%, color-mix(in srgb, var(--df-white) 20%, transparent))",
            opacity: rimOpacity ?? "var(--lg-rim-opacity, 0.6)",
            mixBlendMode: "screen",
          }}
        />
      )}
      {children}
    </div>
  );
}
